### ISSUE TITLE
OSError when running GroupClassDiscVis.py

### ISSUE THREAD

**Issue by ngonthier** [GlowingHorse/class-discriminative-vis#1]
Hello,

When I tried to run the GroupClassDiscVis.py file, I got the following error : 
"OSError: ./dog_cat224/golden retriever_IGSG/IGSG_mixed4d_golden retriever.txt not found." 

And when I look inside the /dog_cat224/golden retriever_IGSG/ folder it is empty. 

The error is raised by the np.loadtxt function inside the compute_igsg function. 

I don't know how to solve it. 

Moreover, to run the script, I needed to not import the following function : raw_class_group_attr, compute_all_am_shap, compute_shap_test from  utils.attr_computing file.

For your information, I am using Python 3.7 on Windows.

Best,

**Comment by GlowingHorse** [comment]
Sorry for late replying. You can generate it by change
> /# whether load the pre-computed feature attribution
> flag_read_attr = False
> /# Shapley value computing method, "Shap" or "IGSG"
> flag1 = "IGSG"

in GroupClassDiscVis.py.
